### ISSUE TITLE
XAPP1251 xvcServer.c source requires attribution to xvcd

### ISSUE THREAD

**Issue by adrianh-xlnx** [Xilinx/XilinxVirtualCable#1]
"xvcServer.c" requires attribution to "xvcd.c" (https://github.com/tmbinc/xvcd) by @tmbinc. In order to correct this issue all previous versions of "xvcServer.c" have been removed and the [xvcServer.c](https://github.com/Xilinx/XilinxVirtualCable/blob/master/XAPP1251/src/xvcServer.c) file has been updated with the corrected attribution.

@tmbinc please review the fix to [xvcServer.c](https://github.com/Xilinx/XilinxVirtualCable/blob/master/XAPP1251/src/xvcServer.c) and let us know if this issue is resolved.

**Comment by tmbinc** [comment]
Looks good to me. Thank you! (Also for keeping the changes as CC0; very much appreciated.)
