### ISSUE TITLE
for what this loop???

### ISSUE THREAD

**Issue by sirius13** [Xilinx/XilinxVirtualCable#4]
https://github.com/Xilinx/XilinxVirtualCable/blob/d2c2babe6ebd87f810da0e63ad04e9c4c16efa37/XAPP1251/src/xvcServer.c#L143

**Comment by prashant-mehta** [comment]
Hi @sirius13,
Before that line, we set bit 0 (Enable Shift operation) of the CTRL register to 1 to start the transfer over JTAG. This Enable Shift Operation bit is self-clearing. So, at [line #143](https://github.com/Xilinx/XilinxVirtualCable/blob/d2c2babe6ebd87f810da0e63ad04e9c4c16efa37/XAPP1251/src/xvcServer.c#L143), we poll this register to find out when the JTAG shift has been completed before copying the TDO data.
Additional details of the AXI-4Lite to JTAG controller IP are in [XAPP1251](https://docs.xilinx.com/v/u/en-US/xapp1251-xvc-zynq-petalinux).

**Comment by prshant-mehta** [comment]
I am closing this issue since the question was answered.
